# Generated by Django 4.0.2 on 2022-03-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='requests',
            field=models.TextField(null=True),
        ),
    ]
