# Generated by Django 4.0.2 on 2022-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_player_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='domain',
            field=models.CharField(choices=[('Web Dev', 'Web Development')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='software',
            field=models.CharField(choices=[('code', 'VS Code')], max_length=10, null=True),
        ),
    ]
