# Generated by Django 4.0.2 on 2022-05-01 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_player_login_time_player_logout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1003, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1003, null=True)),
                ('domain', models.ManyToManyField(to='Users.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=datetime.datetime(2022, 5, 1, 12, 34, 49, 888895))),
                ('logout_time', models.DateTimeField(default=datetime.datetime(2022, 5, 1, 12, 34, 49, 888918))),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.domain')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.player')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.software')),
            ],
        ),
    ]
