# Generated by Django 4.0.2 on 2022-05-01 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_domain_technology_or_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 12, 42, 35, 404379)),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 12, 42, 35, 404401)),
        ),
    ]
