# Generated by Django 4.0.2 on 2022-05-01 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_session_login_time_alter_session_logout_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='technology_or_platform',
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 12, 49, 57, 717781)),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 12, 49, 57, 717804)),
        ),
    ]
