# Generated by Django 4.0.2 on 2022-05-01 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_remove_domain_technology_or_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='frameWork_or_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.framework_or_platform'),
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 12, 54, 38, 542178)),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 12, 54, 38, 542199)),
        ),
    ]
