# Generated by Django 4.0.2 on 2022-05-01 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_session_framework_or_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 18, 46, 49, 538869)),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 18, 46, 49, 538890)),
        ),
    ]
