# Generated by Django 4.0.2 on 2022-05-01 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_session_login_time_alter_session_logout_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='software',
            field=models.ManyToManyField(to='Users.Software'),
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 18, 49, 9, 304518)),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 18, 49, 9, 304544)),
        ),
    ]
