# Generated by Django 4.0.2 on 2022-05-01 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_software_domain_domain_software_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='player',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='logout_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='software',
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 18, 53, 5, 468473)),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 18, 53, 5, 468496)),
        ),
    ]
