# Generated by Django 4.0.2 on 2022-05-01 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_remove_player_domain_remove_player_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='executable',
            field=models.CharField(max_length=1003, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 20, 58, 18, 289969)),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 20, 58, 18, 290001)),
        ),
    ]
