# Generated by Django 4.0.2 on 2022-05-09 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_alter_session_login_time_alter_session_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 0, 45, 51, 847243)),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 0, 45, 51, 847267)),
        ),
    ]
