# Generated by Django 4.0.2 on 2022-05-09 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_alter_session_login_time_alter_session_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='domain_short',
            field=models.CharField(max_length=1003, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 1, 50, 24, 536428)),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 1, 50, 24, 536450)),
        ),
    ]
